window.KN121 = {
seating: ["ht","ra","lb","ya","nu","yb","lk","sh","utj","rz","oy","nm"],
factions: {
  lk: {seats:32, n:{en:"Likud",he:"הליכוד",ar:"الليكود",ru:"Ликуд"}, next:{en:"Likud",he:"הליכוד",ar:"الليكود",ru:"Ликуд"}},
  ya: {seats:24, n:{en:"Yesh Atid",he:"יש עתיד",ar:"يش عتيد",ru:"Еш Атид"}, next:{en:"Together (with Bennett 2026)",he:"ביחד (עם בנט 2026)",ar:"معًا (مع بينيت 2026)",ru:"«Вместе» (с «Беннет 2026»)"}},
  nu: {seats:12, n:{en:"National Unity",he:"המחנה הממלכתי",ar:"المعسكر الرسمي",ru:"«Государственный лагерь»"}, next:{en:"Blue and White",he:"כחול לבן",ar:"أزرق أبيض",ru:"«Кахоль-лаван»"}},
  sh: {seats:11, n:{en:"Shas",he:"ש״ס",ar:"شاس",ru:"ШАС"}, next:{en:"Shas",he:"ש״ס",ar:"شاس",ru:"ШАС"}},
  utj:{seats:7, n:{en:"United Torah Judaism",he:"יהדות התורה",ar:"يهدوت هتوراه",ru:"«Яхадут ха-Тора»"}, next:{en:"United Torah Judaism",he:"יהדות התורה",ar:"يهدوت هتوراه",ru:"«Яхадут ха-Тора»"}},
  rz: {seats:7, n:{en:"Religious Zionism",he:"הציונות הדתית",ar:"الصهيونية الدينية",ru:"«Религиозный сионизм»"}, next:{en:"Religious Zionism (with Zehut)",he:"הציונות הדתית (עם זהות)",ar:"الصهيونية الدينية (مع زهوت)",ru:"«Религиозный сионизм» (с «Зеут»)"}},
  oy: {seats:6, n:{en:"Otzma Yehudit",he:"עוצמה יהודית",ar:"عوتسما يهوديت",ru:"«Оцма Иегудит»"}, next:{en:"Otzma Yehudit",he:"עוצמה יהודית",ar:"عوتسما يهوديت",ru:"«Оцма Иегудит»"}},
  yb: {seats:6, n:{en:"Yisrael Beiteinu",he:"ישראל ביתנו",ar:"يسرائيل بيتينو",ru:"«Наш дом Израиль»"}, next:{en:"Yisrael Beiteinu",he:"ישראל ביתנו",ar:"يسرائيل بيتينو",ru:"«Наш дом Израиль»"}},
  ra: {seats:5, n:{en:"Ra'am",he:"רע״מ",ar:"القائمة الموحدة",ru:"РААМ"}, next:{en:"Ra'am (with Yoav Segalovitz)",he:"רע״מ (עם יואב סגלוביץ׳)",ar:"القائمة الموحدة (مع يوآف سيغالوفيتش)",ru:"РААМ (с Йоавом Сегаловичем)"}},
  ht: {seats:5, n:{en:"Hadash–Ta'al",he:"חד״ש–תע״ל",ar:"الجبهة–العربية للتغيير",ru:"Хадаш–Таль"}, next:{en:"Joint List",he:"הרשימה המשותפת",ar:"القائمة المشتركة",ru:"«Объединённый список»"}},
  lb: {seats:4, n:{en:"Labor",he:"העבודה",ar:"العمل",ru:"«Авода»"}, next:{en:"The Democrats",he:"הדמוקרטים",ar:"الديمقراطيون",ru:"«Демократы»"}},
  nm: {seats:1, n:{en:"Noam",he:"נעם",ar:"نوعم",ru:"«Ноам»"}, next:null}
},
ui: {
 en: {name:"English", tag:"The 121st seat", proto:"Prototype · 4 of ~40 bills · texts, tallies and excerpts are illustrative drafts, not verified",
  navVote:"Vote", navResults:"Your matches", progress:"{n} of {t} bills",
  for:"For", against:"Against", abstain:"Abstain", skip:"Skip — I don’t know enough", skipped:"Skipped", knesset:"KNESSET 25",
  says:"What it says", pro:"Supporters argue", con:"Opponents argue", ai:"AI-drafted from {s} sources · hand-checked",
  readMore:"Read the full reasoning", why:"Why this bill?", sponsorHidden:"Sponsor hidden until you vote",
  howVoted:"How the Knesset voted", you:"You", lgFor:"For", lgAgainst:"Against", lgAbstain:"Abstained", lgAbsent:"Absent", lgInferred:"Boycott, counted as against",
  absentNote:"{x} of 120 members did not vote. We treat absence as missing data, never as abstention.",
  sided:"Voted like you", sidedNone:"No faction’s majority voted like you.", next:"Next bill", seeMatches:"See your matches",
  soFar:"Your seat so far", soFarEmpty:"Vote on a bill to see where you would sit.", conf:["Low confidence","Medium confidence","High confidence"],
  results:"Where you would sit", basedOn:"Based on {n} votes · bars show the 90% range",
  historic:"This compares your answers with how 25th-Knesset factions actually voted. It is a record of the past, not a prediction of what any 2026 list will do.",
  runs:"2026: {x}", notRunning:"2026: no separate list",
  newLists:"Lists made up mostly of new candidates have little or no record in this Knesset, so we can’t match them. Your match with them is unknown — not zero.",
  sepT:"What would separate {a} from {b}", sepNone:"None of the remaining bills separates these two. Your answers so far put them level.", sepGo:"Vote on it",
  keepVoting:"Keep voting to narrow the range", yourVotes:"Your votes",
  membersT:"Individual members", membersB:"Members of the same faction almost always vote together, so we match parties first. Member-level matches unlock after {k} votes ({n} so far).",
  privacy:"Your votes are stored only on this device. No account, no tracking.", clear:"Clear my votes",
  back:"Back to the vote", sources:"Sources", sample:"sample excerpt", sourcesNote:"Sample sources — in the full app each links to the original document.",
  fallback:"The long-form analysis is published in Hebrew and English for now. The {l} version is waiting for native-speaker review, so it is shown in English.",
  corrections:"Reader corrections: coming in a later version.",
  h:["What the bill does","The supporters’ case","The opponents’ case","How this was drafted"], later:"What happened next",
  types:{law:"Bill text",cmte:"Committee protocol",plen:"Plenum protocol",rsch:"Knesset Research Center",legal:"Legal opinion",data:"Data",court:"Court ruling",ngo:"Position paper"},
  done:"That’s every bill in this prototype.", doneB:"The full app would continue with the next most informative of ~40 hand-checked bills.",
  queueT:"Queue · information gain × salience", queueNote:"Bills that would split your current top matches rise. Bills that repeat a split you’ve already answered sink.",
  algo:"{ig} bits expected · salience {s}/10 · {o}% overlap with bills you answered", toastEnd:"Recorded. Party votes are revealed in your results.", noData:"no record"},
 he: {name:"עברית", tag:"המושב ה־121", proto:"אב־טיפוס · 4 מתוך כ־40 הצעות · הנוסחים, תוצאות ההצבעה והציטוטים הם טיוטות להמחשה ולא נבדקו",
  navVote:"הצבעה", navResults:"ההתאמות שלך", progress:"{n} מתוך {t} הצעות",
  for:"בעד", against:"נגד", abstain:"נמנע/ת", skip:"דילוג — אין לי מספיק מידע", skipped:"דילגת", knesset:"הכנסת ה־25",
  says:"מה ההצעה קובעת", pro:"התומכים טוענים", con:"המתנגדים טוענים", ai:"נוסח בידי AI מתוך {s} מקורות · נבדק ידנית",
  readMore:"לנימוקים המלאים", why:"למה ההצעה הזאת?", sponsorHidden:"זהות המגישים תיחשף אחרי ההצבעה",
  howVoted:"איך הצביעה הכנסת", you:"את/ה", lgFor:"בעד", lgAgainst:"נגד", lgAbstain:"נמנעו", lgAbsent:"לא הצביעו", lgInferred:"חרם, נספר כ״נגד״",
  absentNote:"{x} מתוך 120 חברי הכנסת לא הצביעו. היעדרות נחשבת אצלנו לחוסר מידע, אף פעם לא להימנעות.",
  sided:"הצביעו כמוך", sidedNone:"אף סיעה לא הצביעה ברובה כמוך.", next:"להצעה הבאה", seeMatches:"להתאמות שלך",
  soFar:"המושב שלך עד כה", soFarEmpty:"הצביעו על הצעה כדי לראות היכן הייתם יושבים.", conf:["ודאות נמוכה","ודאות בינונית","ודאות גבוהה"],
  results:"איפה היית יושב/ת", basedOn:"על סמך {n} הצבעות · הפסים מציגים טווח של 90%",
  historic:"ההשוואה היא בין התשובות שלך לבין האופן שבו סיעות הכנסת ה־25 הצביעו בפועל. זה תיעוד של העבר, לא תחזית למה שרשימה כלשהי תעשה ב־2026.",
  runs:"2026: {x}", notRunning:"2026: אין רשימה נפרדת",
  newLists:"לרשימות שמורכבות בעיקר ממועמדים חדשים אין כמעט רקורד בכנסת הזו, ולכן אי אפשר להתאים אותן. ההתאמה שלך אליהן לא ידועה — היא לא אפס.",
  sepT:"מה יכריע בין {a} לבין {b}", sepNone:"אף אחת מההצעות שנותרו לא מבדילה בין השתיים. לפי התשובות שלך עד כה הן שוות.", sepGo:"להצבעה עליה",
  keepVoting:"המשיכו להצביע כדי לצמצם את הטווח", yourVotes:"ההצבעות שלך",
  membersT:"חברי כנסת בודדים", membersB:"חברי אותה סיעה מצביעים כמעט תמיד יחד, ולכן אנחנו מתאימים קודם מפלגות. התאמה לחברי כנסת בודדים תיפתח אחרי {k} הצבעות ({n} עד כה).",
  privacy:"ההצבעות שלך נשמרות רק במכשיר הזה. בלי חשבון, בלי מעקב.", clear:"מחיקת ההצבעות שלי",
  back:"חזרה להצבעה", sources:"מקורות", sample:"ציטוט לדוגמה", sourcesNote:"מקורות לדוגמה — בגרסה המלאה כל מקור מקושר למסמך המקורי.",
  fallback:"", corrections:"תיקונים מהקוראים: בגרסה עתידית.",
  h:["מה ההצעה עושה","טיעוני התומכים","טיעוני המתנגדים","איך זה נוסח"], later:"מה קרה אחר כך",
  types:{law:"נוסח ההצעה",cmte:"פרוטוקול ועדה",plen:"פרוטוקול מליאה",rsch:"מרכז המחקר והמידע של הכנסת",legal:"חוות דעת משפטית",data:"נתונים",court:"פסק דין",ngo:"נייר עמדה"},
  done:"הצבעת על כל ההצעות באב־הטיפוס.", doneB:"באפליקציה המלאה ההמשך יהיה ההצעה האינפורמטיבית הבאה מתוך כ־40 הצעות שנבדקו ידנית.",
  queueT:"התור · רווח מידע × עניין ציבורי", queueNote:"הצעות שמבדילות בין ההתאמות המובילות שלך עולות בתור. הצעות שחוזרות על פיצול שכבר ענית עליו יורדות.",
  algo:"{ig} ביט צפוי · עניין ציבורי {s}/10 · חפיפה של {o}% להצעות שענית עליהן", toastEnd:"נרשם. הצבעות הסיעות ייחשפו בתוצאות.", noData:"אין רקורד"},
 ar: {name:"العربية", tag:"المقعد الـ121", proto:"نموذج أولي · 4 من نحو 40 اقتراحًا · النصوص ونتائج التصويت والاقتباسات مسودات توضيحية غير مُدقَّقة",
  navVote:"التصويت", navResults:"تطابقاتك", progress:"{n} من {t} اقتراحات",
  for:"مع", against:"ضد", abstain:"امتناع", skip:"تخطٍّ — لا أعرف ما يكفي", skipped:"تخطّيت", knesset:"الكنيست الـ25",
  says:"ماذا ينص الاقتراح", pro:"يقول المؤيدون", con:"يقول المعارضون", ai:"صاغه الذكاء الاصطناعي من {s} مصادر · دُقِّق يدويًا",
  readMore:"اقرأ التعليل الكامل", why:"لماذا هذا الاقتراح؟", sponsorHidden:"هوية مقدّمي الاقتراح تُكشف بعد تصويتك",
  howVoted:"كيف صوّت الكنيست", you:"أنت", lgFor:"مع", lgAgainst:"ضد", lgAbstain:"امتنعوا", lgAbsent:"لم يصوّتوا", lgInferred:"مقاطعة، احتُسبت ضد",
  absentNote:"{x} من أصل 120 عضوًا لم يصوّتوا. نعامل الغياب كبيانات ناقصة، ولا نعدّه امتناعًا أبدًا.",
  sided:"صوّتوا مثلك", sidedNone:"لم تصوّت أغلبية أي كتلة مثلك.", next:"الاقتراح التالي", seeMatches:"اعرض تطابقاتك",
  soFar:"مقعدك حتى الآن", soFarEmpty:"صوّت على اقتراح لترى أين ستجلس.", conf:["ثقة منخفضة","ثقة متوسطة","ثقة عالية"],
  results:"أين ستجلس", basedOn:"استنادًا إلى {n} أصوات · الأشرطة تُظهر نطاق 90%",
  historic:"نقارن إجاباتك بكيفية تصويت كتل الكنيست الـ25 فعليًا. هذا سجلّ للماضي، لا توقّع لما ستفعله أي قائمة في 2026.",
  runs:"2026: {x}", notRunning:"2026: لا قائمة منفصلة",
  newLists:"القوائم المكوّنة في معظمها من مرشحين جدد ليس لها سجل يُذكر في هذا الكنيست، لذا لا يمكننا مطابقتها. تطابقك معها مجهول، لا صفر.",
  sepT:"ما الذي يحسم بين {a} و{b}", sepNone:"لا يفرّق أي من الاقتراحات المتبقية بين الاثنتين. إجاباتك حتى الآن تضعهما متساويتين.", sepGo:"صوّت عليه",
  keepVoting:"واصل التصويت لتضييق النطاق", yourVotes:"أصواتك",
  membersT:"أعضاء الكنيست فرديًا", membersB:"أعضاء الكتلة الواحدة يصوّتون معًا في الغالب، لذلك نطابق الأحزاب أولًا. تُفتح المطابقة مع الأعضاء بعد {k} صوتًا ({n} حتى الآن).",
  privacy:"تُحفظ أصواتك على هذا الجهاز فقط. بلا حساب وبلا تتبّع.", clear:"امسح أصواتي",
  back:"العودة إلى التصويت",
  fallback:"التحليل المطوّل منشور حاليًا بالعبرية والإنجليزية. النسخة العربية بانتظار مراجعة متحدثين أصليين، لذا يُعرض بالإنجليزية.",
  corrections:"تصحيحات القرّاء: في إصدار لاحق.",
  done:"صوّتّ على جميع الاقتراحات في هذا النموذج.", doneB:"في التطبيق الكامل يتواصل التصويت مع الاقتراح الأكثر إفادة التالي من بين نحو 40 اقتراحًا مدقّقًا يدويًا.",
  queueT:"قائمة الانتظار · مكسب المعلومات × الأهمية", queueNote:"ترتفع الاقتراحات التي تفرّق بين أعلى تطابقاتك، وتنخفض تلك التي تكرر انقسامًا أجبت عنه.",
  algo:"{ig} بت متوقع · الأهمية {s}/10 · تداخل {o}% مع ما أجبت عنه", toastEnd:"سُجّل. تُكشف أصوات الكتل في نتائجك.", noData:"لا سجل"},
 ru: {name:"Русский", tag:"121-е место", proto:"Прототип · 4 из ~40 законопроектов · тексты, итоги и цитаты — иллюстративные черновики, не проверены",
  navVote:"Голосование", navResults:"Ваши совпадения", progress:"{n} из {t}",
  for:"За", against:"Против", abstain:"Воздержаться", skip:"Пропустить — мало знаю", skipped:"Пропущено", knesset:"КНЕССЕТ 25-ГО СОЗЫВА",
  says:"Что предлагает закон", pro:"Сторонники считают", con:"Противники считают", ai:"Составлено ИИ по {s} источникам · проверено вручную",
  readMore:"Полное обоснование", why:"Почему этот законопроект?", sponsorHidden:"Авторы будут показаны после вашего голоса",
  howVoted:"Как голосовал Кнессет", you:"Вы", lgFor:"За", lgAgainst:"Против", lgAbstain:"Воздержались", lgAbsent:"Не голосовали", lgInferred:"Бойкот, засчитан как «против»",
  absentNote:"{x} из 120 депутатов не голосовали. Отсутствие мы считаем недостающими данными, а не воздержанием.",
  sided:"Голосовали как вы", sidedNone:"Ни одна фракция в большинстве не голосовала как вы.", next:"Следующий законопроект", seeMatches:"Ваши совпадения",
  soFar:"Ваше место пока", soFarEmpty:"Проголосуйте, чтобы увидеть, где бы вы сидели.", conf:["Низкая уверенность","Средняя уверенность","Высокая уверенность"],
  results:"Где бы вы сидели", basedOn:"На основе {n} голосов · полосы — 90% диапазон",
  historic:"Мы сравниваем ваши ответы с тем, как фракции Кнессета 25-го созыва голосовали на самом деле. Это запись прошлого, а не прогноз того, что сделает какой-либо список в 2026 году.",
  runs:"2026: {x}", notRunning:"2026: нет отдельного списка",
  newLists:"У списков, состоящих в основном из новых кандидатов, почти нет истории голосований в этом Кнессете, поэтому сопоставить их нельзя. Ваше совпадение с ними неизвестно, а не равно нулю.",
  sepT:"Что отличит {a} от {b}", sepNone:"Ни один из оставшихся законопроектов их не различает. По вашим ответам они пока равны.", sepGo:"Проголосовать",
  keepVoting:"Продолжайте, чтобы сузить диапазон", yourVotes:"Ваши голоса",
  membersT:"Отдельные депутаты", membersB:"Депутаты одной фракции почти всегда голосуют вместе, поэтому сначала мы сопоставляем партии. Совпадения с депутатами откроются после {k} голосов (пока {n}).",
  privacy:"Ваши голоса хранятся только на этом устройстве. Без аккаунта и слежки.", clear:"Удалить мои голоса",
  back:"Назад к голосованию",
  fallback:"Подробный анализ пока опубликован на иврите и английском. Русская версия ждёт проверки носителями языка, поэтому показан английский текст.",
  corrections:"Исправления от читателей: в следующей версии.",
  done:"Вы проголосовали по всем законопроектам прототипа.", doneB:"В полной версии дальше пойдёт следующий по информативности из ~40 проверенных вручную законопроектов.",
  queueT:"Очередь · прирост информации × значимость", queueNote:"Выше поднимаются законопроекты, различающие ваших лидеров. Ниже — те, что повторяют уже пройденный раскол.",
  algo:"{ig} бит ожидается · значимость {s}/10 · {o}% совпадения с пройденными", toastEnd:"Записано. Голоса фракций — в ваших результатах.", noData:"нет данных"}
},
bills: [
{ id:"rsn", sal:10, date:"24.07.2023",
  votes:{lk:[32,0,0,0],sh:[11,0,0,0],utj:[7,0,0,0],rz:[7,0,0,0],oy:[6,0,0,0],nm:[1,0,0,0],ya:[0,0,0,24],nu:[0,0,0,12],yb:[0,0,0,6],ra:[0,0,0,5],ht:[0,0,0,5],lb:[0,0,0,4]},
  infer:{ya:1,nu:1,yb:1,ra:1,ht:1,lb:1},
  t:{
   en:{title:"Basic Law: The Judiciary — Reasonableness Amendment", short:"Reasonableness standard", stage:"Third reading · passed 64–0", sponsor:"Constitution Committee (coalition)",
    sum:"Bars all courts, including the Supreme Court, from reviewing decisions by the government, ministers and other elected officials on the grounds that they are “extremely unreasonable”. Other grounds for judicial review remain.",
    pro:"Unelected judges should not overrule elected officials on a standard supporters call vague and subjective. Policy belongs to voters and their representatives, and other legal tools still guard against abuse.",
    con:"Removes one of the few checks on the government in a country with no written constitution and no second chamber. Critics warn it could shield improper appointments and the dismissal of gatekeepers such as the Attorney General.",
    why:"One of the most debated laws of this Knesset — and it cleanly separates the coalition from the opposition.",
    note:"The opposition walked out and did not vote. Because the boycott was declared as a protest, we count it as “against” — an inference, shown with dashed outlines.",
    later:"Struck down by the Supreme Court on 1 January 2024 (8–7)."},
   he:{title:"חוק־יסוד: השפיטה (תיקון – עילת הסבירות)", short:"עילת הסבירות", stage:"קריאה שלישית · התקבלה 64–0", sponsor:"ועדת החוקה (קואליציה)",
    sum:"אוסרת על כל בתי המשפט, כולל בית המשפט העליון, לבקר החלטות של הממשלה, של שרים ושל נבחרי ציבור אחרים בטענה שהן ״בלתי סבירות באופן קיצוני״. עילות ביקורת אחרות נשארות בתוקף.",
    pro:"שופטים שלא נבחרו לא צריכים לבטל החלטות של נבחרי ציבור על סמך אמת מידה שלדברי התומכים היא עמומה וסובייקטיבית. המדיניות שייכת לבוחרים ולנציגיהם, וכלים משפטיים אחרים עדיין מגנים מפני שימוש לרעה בכוח.",
    con:"מבטלת את אחד הבלמים המעטים על הממשלה, במדינה שאין בה חוקה כתובה ואין בית מחוקקים שני. המבקרים מזהירים שהיא עלולה להגן על מינויים פסולים ועל פיטורי שומרי סף כמו היועצת המשפטית לממשלה.",
    why:"אחד החוקים השנויים ביותר במחלוקת בכנסת הזו — והוא מפריד בחדות בין הקואליציה לאופוזיציה.",
    note:"האופוזיציה יצאה מהמליאה ולא הצביעה. מכיוון שהחרם הוכרז כמחאה, אנחנו סופרים אותו כ״נגד״ — זו הסקה, והיא מסומנת בקו מקווקו.",
    later:"בוטל בידי בג״ץ ב־1 בינואר 2024 (8–7)."},
   ar:{title:"قانون أساس: القضاء (تعديل – ذريعة المعقولية)", short:"ذريعة المعقولية", stage:"القراءة الثالثة · أُقرّ 64–0", sponsor:"لجنة الدستور (الائتلاف)",
    sum:"تمنع جميع المحاكم، بما فيها المحكمة العليا، من مراجعة قرارات الحكومة والوزراء وسائر المنتخَبين بحجة أنها «غير معقولة إلى حدٍّ متطرف». وتبقى ذرائع الرقابة القضائية الأخرى سارية.",
    pro:"لا ينبغي لقضاة غير منتخَبين إلغاء قرارات المنتخَبين استنادًا إلى معيار يصفه المؤيدون بأنه غامض وذاتي. السياسات من حق الناخبين وممثليهم، وما زالت أدوات قانونية أخرى تحمي من إساءة استخدام السلطة.",
    con:"تُلغي أحد الضوابط القليلة على الحكومة في دولة بلا دستور مكتوب ولا مجلس تشريعي ثانٍ. ويحذّر المنتقدون من أنها قد تحمي تعيينات غير سليمة وإقالة حرّاس البوابة مثل المستشارة القضائية للحكومة.",
    why:"من أكثر القوانين إثارة للجدل في هذا الكنيست، ويفصل بوضوح بين الائتلاف والمعارضة.",
    note:"انسحبت المعارضة ولم تصوّت. ولأن المقاطعة أُعلنت احتجاجًا، نحتسبها «ضد» — وهذا استنتاج مُعلَّم بإطار متقطع.",
    later:"ألغته المحكمة العليا في 1 كانون الثاني 2024 (8–7)."},
   ru:{title:"Основной закон о судебной власти: поправка о «разумности»", short:"Критерий разумности", stage:"Третье чтение · принят 64–0", sponsor:"Конституционная комиссия (коалиция)",
    sum:"Запрещает всем судам, включая Верховный, отменять решения правительства, министров и других избранных лиц на том основании, что они «крайне неразумны». Остальные основания для судебного контроля сохраняются.",
    pro:"Неизбранные судьи не должны отменять решения избранных политиков по критерию, который сторонники называют размытым и субъективным. Политика — дело избирателей и их представителей, а от злоупотреблений защищают другие правовые механизмы.",
    con:"Убирает один из немногих противовесов правительству в стране без писаной конституции и второй палаты. Критики предупреждают, что это может прикрыть сомнительные назначения и увольнение «стражей», например юридического советника правительства.",
    why:"Один из самых обсуждаемых законов этого созыва — чётко разделяет коалицию и оппозицию.",
    note:"Оппозиция покинула зал и не голосовала. Поскольку бойкот был объявлен протестом, мы засчитываем его как «против» — это вывод, он показан пунктиром.",
    later:"Отменён Верховным судом 1 января 2024 года (8–7)."}
  },
  src:[
   {t:"law", en:"Basic Law: The Judiciary (Amendment), text as passed", he:"חוק־יסוד: השפיטה (תיקון), הנוסח שהתקבל"},
   {t:"rsch", en:"Judicial review on grounds of reasonableness: background brief", he:"ביקורת שיפוטית בעילת הסבירות: סקירת רקע"},
   {t:"cmte", en:"Constitution Committee, session of 11.07.2023", he:"ועדת החוקה, ישיבה מ־11.07.2023"},
   {t:"cmte", en:"Constitution Committee, session of 18.07.2023", he:"ועדת החוקה, ישיבה מ־18.07.2023"},
   {t:"plen", en:"Plenum debate and votes, 23–24.07.2023", he:"דיון והצבעות במליאה, 23–24.07.2023"},
   {t:"legal", en:"Attorney General’s opinion to the Constitution Committee", he:"חוות דעת היועצת המשפטית לממשלה לוועדת החוקה"},
   {t:"court", en:"Supreme Court ruling on the amendment, 01.01.2024", he:"פסק דין בג״ץ בעניין התיקון, 01.01.2024"}
  ],
  deep:{
   en:[
    {h:0, p:[{x:"The amendment adds a clause to Basic Law: The Judiciary: courts may not hear or rule on the reasonableness of decisions by the government, the prime minister, ministers, or other elected officials as set by law.", c:[1]},
             {x:"It leaves other grounds of review in place, such as legality, proportionality and conflict of interest. Supporters and opponents alike treated it as the first step of a broader judicial overhaul.", c:[2,3]}],
     q:{x:"“…a court shall not hear, and shall not issue an order against, the government, the prime minister or a minister… regarding the reasonableness of their decision.”", s:"Bill text, section 1 (translated)"}},
    {h:1, p:[{x:"Supporters, speaking mostly in the Constitution Committee, argued that reasonableness lets judges substitute their own judgement for that of elected officials. They describe it as a vague standard with no clear definition in statute.", c:[3,4]},
             {x:"They also argued that few democracies give courts this power in quite this form, and that ministers remain accountable to the Knesset and to voters.", c:[4,5]}],
     q:{x:"“Reasonableness is in the eyes of the beholder. The question is whose eyes — the voters’ or the judges’.”", s:"Coalition MK · Constitution Committee, 07.2023"}},
    {h:2, p:[{x:"Opponents, including former Attorneys General and much of the legal community, argued that in Israel’s system — one chamber, a Knesset controlled by the coalition, no written constitution — the courts are one of the only checks on executive power.", c:[5,6]},
             {x:"They pointed to cases where the standard had been used, including blocking the appointment of a minister with criminal convictions, and warned it could ease the dismissal of the Attorney General.", c:[6]}],
     q:{x:"“Without this standard, a government can appoint whom it likes and fire whom it likes, as long as it follows procedure.”", s:"Opposition MK · plenum debate, 24.07.2023"}},
    {h:3, p:[{x:"Drafted from the bill text, Constitution Committee protocols, the plenum debate, a Knesset Research Center brief and legal opinions. An argument is included only if speakers from at least two factions made it.", c:[]}]},
    {h:"later", p:[{x:"The Supreme Court struck the amendment down on 1 January 2024, by 8 votes to 7 — the first time it annulled part of a Basic Law.", c:[7]}]}
   ],
   he:[
    {h:0, p:[{x:"התיקון מוסיף סעיף לחוק־יסוד: השפיטה, שלפיו בתי המשפט לא ידונו ולא יכריעו בשאלת סבירותן של החלטות הממשלה, ראש הממשלה, שר או נבחר ציבור אחר כפי שייקבע בחוק.", c:[1]},
             {x:"התיקון אינו נוגע בעילות ביקורת אחרות כמו חוקיות, מידתיות או ניגוד עניינים. גם התומכים וגם המתנגדים ראו בו צעד ראשון במהלך רחב יותר לשינוי מערכת המשפט.", c:[2,3]}],
     q:{x:"״...לא ידון בית משפט ולא ייתן צו נגד הממשלה, ראש הממשלה או שר... בעניין סבירות החלטתם.״", s:"נוסח החוק, סעיף 1"}},
    {h:1, p:[{x:"התומכים, בעיקר בדיוני ועדת החוקה, טענו שעילת הסבירות מאפשרת לשופטים להחליף את שיקול הדעת של נבחרי הציבור בשיקול דעתם שלהם. לדבריהם זו אמת מידה עמומה שאין לה הגדרה ברורה בחקיקה.", c:[3,4]},
             {x:"עוד טענו שדמוקרטיות מעטות מעניקות לבית המשפט סמכות בצורה הזו בדיוק, ושהשרים ממשיכים לתת דין וחשבון לכנסת ולבוחרים.", c:[4,5]}],
     q:{x:"״סבירות היא בעיני המתבונן. השאלה היא בעיני מי — הבוחרים או השופטים.״", s:"ח״כ מהקואליציה · ועדת החוקה, 07.2023"}},
    {h:2, p:[{x:"המתנגדים, ובהם יועצים משפטיים לממשלה לשעבר וחלק גדול מהקהילה המשפטית, טענו שבשיטה הישראלית — בית אחד, כנסת שבשליטת הקואליציה, בלי חוקה כתובה — בתי המשפט הם אחד הבלמים היחידים על הרשות המבצעת.", c:[5,6]},
             {x:"הם הצביעו על מקרים שבהם נעשה שימוש בעילה, כמו מניעת מינוי של שר שהורשע בפלילים, והזהירו שהיא עלולה להקל על פיטורי היועצת המשפטית לממשלה.", c:[6]}],
     q:{x:"״בלי העילה הזו, ממשלה יכולה למנות את מי שתרצה ולפטר את מי שתרצה, כל עוד היא עומדת בנהלים.״", s:"ח״כ מהאופוזיציה · דיון במליאה, 24.07.2023"}},
    {h:3, p:[{x:"נוסח מתוך נוסח החוק, פרוטוקולים של ועדת החוקה, הדיון במליאה, סקירה של מרכז המחקר והמידע של הכנסת וחוות דעת משפטיות. טיעון נכלל רק אם הועלה בידי דוברים משתי סיעות לפחות.", c:[]}]},
    {h:"later", p:[{x:"בג״ץ ביטל את התיקון ב־1 בינואר 2024, ברוב של 8 מול 7 — הפעם הראשונה שבה בוטל חלק מחוק־יסוד.", c:[7]}]}
   ]
  }
},
{ id:"dp", sal:9, date:"01.03.2023",
  votes:{lk:[27,0,0,5],sh:[7,0,0,4],utj:[2,0,0,5],rz:[7,0,0,0],oy:[6,0,0,0],nm:[1,0,0,0],yb:[5,0,0,1],ya:[0,0,0,24],nu:[0,0,0,12],ra:[0,2,0,3],ht:[0,5,0,0],lb:[0,2,0,2]},
  t:{
   en:{title:"Penal Law — Death Penalty for Terrorists", short:"Death penalty", stage:"Preliminary reading · passed 55–9", sponsor:"Private bill (Otzma Yehudit)",
    sum:"Would allow courts to sentence to death a person convicted of murder driven by racism or hostility toward the public, aimed at harming the State of Israel. It would also make it easier for military courts in the West Bank to impose the sentence.",
    pro:"Justice for victims’ families and a deterrent against attacks. Supporters also argue it removes the incentive to kidnap Israelis in order to bargain for the release of convicted attackers.",
    con:"Security officials have long doubted it deters attackers who expect to die; executions could fuel violence and endanger Israelis held abroad. It is irreversible if a court errs, and in practice would apply almost only to Palestinians.",
    why:"Tests how you weigh deterrence and justice against irreversibility — and it splits the opposition."},
   he:{title:"חוק העונשין (תיקון – עונש מוות למחבלים)", short:"עונש מוות למחבלים", stage:"קריאה טרומית · התקבלה 55–9", sponsor:"הצעת חוק פרטית (עוצמה יהודית)",
    sum:"תאפשר לבית המשפט לגזור עונש מוות על מי שהורשע ברצח ממניע של גזענות או עוינות כלפי ציבור, במטרה לפגוע במדינת ישראל. בנוסף, תקל על בתי הדין הצבאיים ביהודה ושומרון להטיל את העונש.",
    pro:"צדק למשפחות הנרצחים והרתעה מפני פיגועים. התומכים טוענים גם שהחוק יבטל את התמריץ לחטוף ישראלים כדי לסחוט שחרור של מחבלים כלואים.",
    con:"גורמי ביטחון הטילו ספק לאורך השנים ביכולת להרתיע מחבלים שמוכנים למות; הוצאות להורג עלולות להצית אלימות ולסכן ישראלים המוחזקים בחו״ל. העונש בלתי הפיך אם בית המשפט טועה, ובפועל יחול כמעט רק על פלסטינים.",
    why:"בודקת איך אתם שוקלים הרתעה וצדק מול עונש בלתי הפיך — ומפצלת את האופוזיציה."},
   ar:{title:"قانون العقوبات (تعديل – عقوبة الإعدام للإرهابيين)", short:"عقوبة الإعدام", stage:"القراءة التمهيدية · أُقرّ 55–9", sponsor:"اقتراح قانون خاص (عوتسما يهوديت)",
    sum:"يتيح للمحاكم الحكم بالإعدام على من أُدين بالقتل بدافع العنصرية أو العداء تجاه جمهور، بهدف المسّ بدولة إسرائيل. كما يسهّل على المحاكم العسكرية في الضفة الغربية فرض هذه العقوبة.",
    pro:"إنصاف لعائلات الضحايا وردع للهجمات. ويرى المؤيدون أيضًا أنه يلغي الدافع لخطف إسرائيليين بهدف المساومة على إطلاق سراح منفذي هجمات مُدانين.",
    con:"شكّك مسؤولون أمنيون طويلًا في قدرته على ردع مهاجمين يتوقعون الموت؛ وقد تؤجّج الإعدامات العنف وتعرّض إسرائيليين محتجَزين في الخارج للخطر. العقوبة لا رجعة فيها إن أخطأت المحكمة، وستُطبَّق عمليًا على الفلسطينيين وحدهم تقريبًا.",
    why:"يختبر كيف توازن بين الردع والعدالة من جهة واستحالة التراجع من جهة أخرى، ويقسم المعارضة."},
   ru:{title:"Уголовный кодекс: смертная казнь для террористов", short:"Смертная казнь", stage:"Предварительное чтение · принят 55–9", sponsor:"Частный законопроект («Оцма Иегудит»)",
    sum:"Позволит судам приговаривать к смертной казни осуждённых за убийство на почве расизма или вражды к обществу с целью нанести ущерб Государству Израиль. Также упростит вынесение такого приговора военными судами на Западном берегу.",
    pro:"Справедливость для семей жертв и сдерживание терактов. Сторонники также считают, что закон лишит смысла похищения израильтян ради обмена на осуждённых террористов.",
    con:"Силовики давно сомневаются, что закон остановит тех, кто готов умереть; казни могут разжечь насилие и подвергнуть опасности израильтян, удерживаемых за рубежом. Ошибку суда будет не исправить, а на практике закон почти полностью касается палестинцев.",
    why:"Проверяет, как вы соотносите сдерживание и справедливость с необратимостью наказания, — и раскалывает оппозицию."}
  },
  src:[
   {t:"law", en:"Penal Law (Amendment – Death Penalty for Terrorists), bill and explanatory notes", he:"חוק העונשין (תיקון – עונש מוות למחבלים), הצעה ודברי הסבר"},
   {t:"rsch", en:"The death penalty in Israeli law: background brief", he:"עונש המוות בדין הישראלי: סקירת רקע"},
   {t:"plen", en:"Plenum debate, preliminary reading, 01.03.2023", he:"דיון במליאה, קריאה טרומית, 01.03.2023"},
   {t:"rsch", en:"Deterrent effect of capital punishment: review of studies", he:"השפעה מרתיעה של עונש מוות: סקירת מחקרים"},
   {t:"cmte", en:"National Security Committee, session on the bill", he:"הוועדה לביטחון לאומי, דיון בהצעה"},
   {t:"ngo", en:"Civil-society position papers submitted to the committee", he:"ניירות עמדה של ארגוני חברה אזרחית שהוגשו לוועדה"}
  ],
  deep:{
   en:[
    {h:0, p:[{x:"The bill amends the Penal Law so that a person who intentionally or indifferently causes the death of an Israeli citizen, out of racism or hostility toward a public and with the aim of harming the State of Israel, may be sentenced to death.", c:[1]},
             {x:"It also amends military law in the West Bank so that a death sentence would no longer require a unanimous panel. Israel’s civilian courts have carried out only one execution — Adolf Eichmann, in 1962.", c:[1,2]}],
     q:{x:"“…whoever caused the death of an Israeli citizen… out of racism or hostility toward a public…”", s:"Bill text, section 1 (translated)"}},
    {h:1, p:[{x:"Supporters framed the bill as moral clarity: those who murder civilians for nationalist reasons should face the gravest penalty the law allows.", c:[3]},
             {x:"They also argued that convicted attackers today expect to be freed in future prisoner exchanges, which in their view encourages kidnappings.", c:[3,4]}],
     q:{x:"“A terrorist who knows he will sit in prison and be released in a deal is not deterred.”", s:"Coalition MK · plenum, 01.03.2023"}},
    {h:2, p:[{x:"Opponents cited past assessments by security officials doubting the deterrent effect on attackers who expect to die, and warned that executions could trigger retaliation and endanger Israelis held captive.", c:[4,5]},
             {x:"Human-rights groups and some legal scholars added that the sentence is irreversible if a court errs, and that as written the bill would apply in practice almost only to Palestinians.", c:[5,6]}],
     q:{x:"“Every sentence we carry out would hand our enemies a new martyr.”", s:"Opposition MK · plenum, 01.03.2023"}},
    {h:3, p:[{x:"Drafted from the bill and its explanatory notes, the plenum debate, Knesset Research Center reviews of the law and of deterrence studies, and positions submitted by security bodies and civil-society groups.", c:[]}]}
   ],
   he:[
    {h:0, p:[{x:"ההצעה מתקנת את חוק העונשין כך שמי שגרם במתכוון או באדישות למותו של אזרח ישראלי, ממניע של גזענות או עוינות כלפי ציבור ובמטרה לפגוע במדינת ישראל, יהיה צפוי לעונש מוות.", c:[1]},
             {x:"היא גם משנה את הדין הצבאי ביהודה ושומרון כך שגזר דין מוות לא יחייב עוד הרכב פה אחד. בתי המשפט האזרחיים בישראל הוציאו להורג אדם אחד בלבד — אדולף אייכמן, ב־1962.", c:[1,2]}],
     q:{x:"״...מי שגרם במתכוון או באדישות למותו של אזרח ישראלי... ממניע של גזענות או עוינות כלפי ציבור...״", s:"נוסח ההצעה, סעיף 1"}},
    {h:1, p:[{x:"התומכים הציגו את ההצעה כבהירות מוסרית: מי שרוצח אזרחים ממניע לאומני צריך לעמוד מול העונש החמור ביותר שהחוק מאפשר.", c:[3]},
             {x:"עוד טענו שכיום מחבלים שהורשעו מצפים להשתחרר בעסקאות עתידיות, ולדעתם הדבר מעודד חטיפות.", c:[3,4]}],
     q:{x:"״מחבל שיודע שהוא יישב בכלא וישתחרר בעסקה — לא מורתע.״", s:"ח״כ מהקואליציה · מליאה, 01.03.2023"}},
    {h:2, p:[{x:"המתנגדים הזכירו הערכות עבר של גורמי ביטחון שהטילו ספק בהרתעה של מחבלים שמצפים למות, והזהירו שהוצאות להורג עלולות להוביל לנקמה ולסכן ישראלים שבויים.", c:[4,5]},
             {x:"ארגוני זכויות אדם וחלק מהמשפטנים הוסיפו שהעונש בלתי הפיך אם בית המשפט טועה, ושבנוסחה הנוכחי ההצעה תחול בפועל כמעט רק על פלסטינים.", c:[5,6]}],
     q:{x:"״בכל גזר דין שנבצע ניתן לאויבינו שהיד חדש.״", s:"ח״כ מהאופוזיציה · מליאה, 01.03.2023"}},
    {h:3, p:[{x:"נוסח מתוך ההצעה ודברי ההסבר, הדיון במליאה, סקירות של מרכז המחקר והמידע של הכנסת על הדין ועל מחקרי הרתעה, ועמדות שהגישו גורמי ביטחון וארגוני חברה אזרחית.", c:[]}]}
   ]
  }
},
{ id:"cu", sal:8, date:"",
  votes:{yb:[6,0,0,0],ya:[20,0,0,4],lb:[4,0,0,0],nu:[8,0,0,4],ht:[3,0,0,2],lk:[0,28,0,4],sh:[0,11,0,0],utj:[0,7,0,0],rz:[0,7,0,0],oy:[0,6,0,0],nm:[0,1,0,0],ra:[0,4,0,1]},
  t:{
   en:{title:"Civil Union Bill", short:"Civil unions", stage:"Preliminary reading · rejected 41–64", sponsor:"Private bill (Yisrael Beiteinu)",
    sum:"Would let any two adults register a civil union in Israel, with the same rights and duties as a married couple, without going through a religious authority.",
    pro:"Hundreds of thousands of Israelis — including many immigrants not recognised as Jewish, and same-sex couples — cannot marry here. The state should not force people through religious institutions to start a family.",
    con:"Opponents say it would erode the shared definition of marriage that holds the Jewish people together and deepen splits over who is a Jew. Jewish and Muslim religious parties alike want family law to stay with religious courts.",
    why:"Here the usual camps reshuffle: Ra'am votes with the religious right, Yisrael Beiteinu with the secular left."},
   he:{title:"הצעת חוק ברית הזוגיות", short:"ברית הזוגיות", stage:"קריאה טרומית · נדחתה 41–64", sponsor:"הצעת חוק פרטית (ישראל ביתנו)",
    sum:"תאפשר לכל שני בגירים להירשם בישראל בברית זוגיות, עם אותן זכויות וחובות כמו זוג נשוי, בלי לעבור דרך מוסד דתי.",
    pro:"מאות אלפי ישראלים — בהם עולים רבים שאינם מוכרים כיהודים, וזוגות חד־מיניים — אינם יכולים להינשא כאן. המדינה לא צריכה לחייב אנשים לעבור דרך מוסדות דתיים כדי להקים משפחה.",
    con:"המתנגדים טוענים שהחוק ישחק את ההגדרה המשותפת של נישואים שמאחדת את העם היהודי ויעמיק את הפילוג בשאלה מיהו יהודי. מפלגות דתיות יהודיות ומוסלמיות כאחת רוצות שדיני המשפחה יישארו בידי בתי הדין הדתיים.",
    why:"כאן המחנות הרגילים מתערבבים: רע״מ מצביעה עם הימין הדתי, וישראל ביתנו עם השמאל החילוני."},
   ar:{title:"اقتراح قانون الشراكة المدنية", short:"الشراكة المدنية", stage:"القراءة التمهيدية · رُفض 41–64", sponsor:"اقتراح قانون خاص (يسرائيل بيتينو)",
    sum:"يتيح لأي شخصين بالغين تسجيل شراكة مدنية في إسرائيل، بالحقوق والواجبات نفسها التي للزوجين، من دون المرور بمؤسسة دينية.",
    pro:"مئات آلاف الإسرائيليين — بينهم كثير من المهاجرين غير المعترف بيهوديتهم، والأزواج من الجنس نفسه — لا يستطيعون الزواج هنا. لا ينبغي للدولة أن تُلزم الناس بالمرور عبر مؤسسات دينية لتأسيس أسرة.",
    con:"يقول المعارضون إنه سيُضعف التعريف المشترك للزواج الذي يوحّد الشعب اليهودي ويعمّق الانقسام حول سؤال مَن هو اليهودي. وتريد أحزاب دينية يهودية وإسلامية على حدّ سواء أن تبقى قوانين الأسرة بيد المحاكم الدينية.",
    why:"هنا تتبدّل المعسكرات المعتادة: القائمة الموحدة تصوّت مع اليمين الديني، ويسرائيل بيتينو مع اليسار العلماني."},
   ru:{title:"Законопроект о гражданском союзе", short:"Гражданский союз", stage:"Предварительное чтение · отклонён 41–64", sponsor:"Частный законопроект («Наш дом Израиль»)",
    sum:"Позволит любым двум взрослым зарегистрировать гражданский союз в Израиле — с теми же правами и обязанностями, что у супругов, без обращения к религиозным властям.",
    pro:"Сотни тысяч израильтян — в том числе многие репатрианты, не признанные евреями, и однополые пары — не могут заключить брак в стране. Государство не должно заставлять людей обращаться к религиозным институтам, чтобы создать семью.",
    con:"Противники считают, что закон размоет общее для еврейского народа понятие брака и углубит раскол в вопросе «кто еврей». И еврейские, и мусульманские религиозные партии хотят, чтобы семейное право оставалось за религиозными судами.",
    why:"Здесь привычные лагеря перемешиваются: РААМ голосует с религиозными правыми, «Наш дом Израиль» — со светскими левыми."}
  },
  src:[
   {t:"law", en:"Civil Union Bill, text and explanatory notes", he:"הצעת חוק ברית הזוגיות, נוסח ודברי הסבר"},
   {t:"data", en:"Central Bureau of Statistics: Israelis registered as married abroad", he:"הלמ״ס: ישראלים שנרשמו כנשואים בחו״ל"},
   {t:"plen", en:"Plenum debate, preliminary reading", he:"דיון במליאה, קריאה טרומית"},
   {t:"rsch", en:"Marriage and divorce law in other democracies: comparative review", he:"דיני נישואים וגירושים בדמוקרטיות אחרות: סקירה השוואתית"},
   {t:"ngo", en:"Positions of religious parties and councils on civil unions", he:"עמדות מפלגות ומועצות דתיות בנושא ברית זוגיות"}
  ],
  deep:{
   en:[
    {h:0, p:[{x:"The bill creates a civil registry of couples, run by the state rather than a religious authority. Any two adults may register, regardless of religion or sex.", c:[1]},
             {x:"Registered couples would receive the rights and obligations of married couples in areas such as inheritance, property, tax and parenthood. Religious marriage is unchanged; the bill adds an alternative.", c:[1,4]}],
     q:{x:"“Couples who have registered… shall have the rights and obligations of married spouses.”", s:"Bill text, section 4 (translated)"}},
    {h:1, p:[{x:"Supporters noted that Israel has no civil marriage, so couples who cannot or will not marry through the rabbinate — among them hundreds of thousands of immigrants from the former Soviet Union — marry abroad, often in Cyprus.", c:[2,3]},
             {x:"They framed the bill as freedom of religion and freedom from religion, and pointed out that the state already registers marriages performed abroad.", c:[3]}],
     q:{x:"“A citizen who served in the army cannot marry in the country he defended.”", s:"Opposition MK · plenum debate"}},
    {h:2, p:[{x:"Opponents in the religious parties argued that one shared marriage framework prevents a split in the Jewish people over lineage and status, and that civil unions would make that split permanent.", c:[5]},
             {x:"Ra'am, an Islamist party, also opposed, saying family matters should stay with each community’s religious courts — which is why this vote does not follow coalition lines.", c:[3,5]}],
     q:{x:"“This is not a technical registry. It redefines the Jewish family.”", s:"Coalition MK · plenum debate"}},
    {h:3, p:[{x:"Drafted from the bill text, the plenum debate, a Knesset Research Center comparison of marriage law in other democracies, and Central Bureau of Statistics data on marriages abroad.", c:[]}]}
   ],
   he:[
    {h:0, p:[{x:"ההצעה יוצרת מרשם אזרחי של בני זוג, שמנוהל בידי המדינה ולא בידי מוסד דתי. כל שני בגירים יכולים להירשם, בלי קשר לדת או למין.", c:[1]},
             {x:"בני זוג רשומים יקבלו את הזכויות והחובות של זוג נשוי בתחומים כמו ירושה, רכוש, מס והורות. הנישואים הדתיים לא משתנים — ההצעה מוסיפה חלופה.", c:[1,4]}],
     q:{x:"״בני זוג שנרשמו... יהיו בעלי הזכויות והחובות של בני זוג נשואים.״", s:"נוסח ההצעה, סעיף 4"}},
    {h:1, p:[{x:"התומכים ציינו שבישראל אין נישואים אזרחיים, ולכן זוגות שאינם יכולים או אינם רוצים להינשא ברבנות — ובהם מאות אלפי עולים מברית המועצות לשעבר — נישאים בחו״ל, לרוב בקפריסין.", c:[2,3]},
             {x:"הם הציגו את ההצעה כחופש דת וחופש מדת, וציינו שהמדינה כבר רושמת נישואים שנערכו בחו״ל.", c:[3]}],
     q:{x:"״אזרח ששירת בצבא לא יכול להתחתן במדינה שעליה הגן.״", s:"ח״כ מהאופוזיציה · דיון במליאה"}},
    {h:2, p:[{x:"מתנגדים מהמפלגות הדתיות טענו שמסגרת נישואים משותפת אחת מונעת פיצול של העם היהודי סביב שאלות של ייחוס ומעמד, ושברית זוגיות תהפוך את הפיצול לקבוע.", c:[5]},
             {x:"גם רע״מ, מפלגה אסלאמית, התנגדה בטענה שענייני המשפחה צריכים להישאר בבתי הדין הדתיים של כל עדה — ולכן ההצבעה הזו לא מתחלקת לפי קווי הקואליציה.", c:[3,5]}],
     q:{x:"״זה לא מרשם טכני. זו הגדרה מחדש של המשפחה היהודית.״", s:"ח״כ מהקואליציה · דיון במליאה"}},
    {h:3, p:[{x:"נוסח מתוך נוסח ההצעה, הדיון במליאה, השוואה של מרכז המחקר והמידע של הכנסת לדיני נישואים בדמוקרטיות אחרות, ונתוני הלמ״ס על נישואים בחו״ל.", c:[]}]}
   ]
  }
},
{ id:"dr", sal:10, date:"06.2024",
  votes:{lk:[31,1,0,0],sh:[11,0,0,0],utj:[7,0,0,0],rz:[7,0,0,0],oy:[6,0,0,0],nm:[1,0,0,0],ya:[0,24,0,0],nu:[0,12,0,0],yb:[0,6,0,0],ra:[0,5,0,0],ht:[0,5,0,0],lb:[0,4,0,0]},
  t:{
   en:{title:"Military Service Law — Yeshiva Student Enlistment", short:"Haredi enlistment", stage:"Continuity vote · passed 63–57", sponsor:"Government bill",
    sum:"Would gradually raise the number of Haredi yeshiva students drafted each year through collective targets rather than individual obligations, and lower the age of exemption from service.",
    pro:"A gradual path is the only one that can work without tearing Haredi society apart. Torah study is itself a service to the nation, and forced mass conscription has failed before.",
    con:"Entrenches inequality while reservists carry an unprecedented burden. Targets are too low and sanctions too weak, and critics say it sidesteps the Supreme Court’s position that blanket exemptions have no legal basis.",
    why:"For many voters, the defining issue of this Knesset term."},
   he:{title:"חוק שירות הביטחון (תיקון – שילוב תלמידי ישיבות)", short:"גיוס חרדים", stage:"החלת דין רציפות · התקבלה 63–57", sponsor:"הצעת חוק ממשלתית",
    sum:"תעלה בהדרגה את מספר תלמידי הישיבות החרדים שמתגייסים בכל שנה, באמצעות יעדי גיוס קבוצתיים במקום חובה אישית, ותוריד את גיל הפטור משירות.",
    pro:"רק מסלול הדרגתי יכול לעבוד בלי לקרוע את החברה החרדית. לימוד תורה הוא בעצמו שירות לאומה, וגיוס כפוי בהיקף רחב כבר נכשל בעבר.",
    con:"מקבעת אי־שוויון בזמן שאנשי המילואים נושאים בנטל חסר תקדים. היעדים נמוכים מדי והסנקציות חלשות מדי, ולדברי המבקרים ההצעה עוקפת את עמדת בג״ץ שלפיה אין בסיס חוקי לפטור גורף.",
    why:"עבור בוחרים רבים — הסוגיה המכרעת של הקדנציה הזו."},
   ar:{title:"قانون خدمة الأمن (تعديل – تجنيد طلاب المدارس الدينية)", short:"تجنيد الحريديم", stage:"تصويت على الاستمرارية · أُقرّ 63–57", sponsor:"اقتراح قانون حكومي",
    sum:"يرفع تدريجيًا عدد طلاب المدارس الدينية الحريديم المجنَّدين سنويًا عبر أهداف تجنيد جماعية بدل الواجب الفردي، ويخفّض سنّ الإعفاء من الخدمة.",
    pro:"المسار التدريجي هو الوحيد القابل للنجاح من دون تمزيق المجتمع الحريدي. فدراسة التوراة بحد ذاتها خدمة للأمة، والتجنيد القسري الواسع فشل من قبل.",
    con:"يكرّس اللامساواة في حين يتحمّل جنود الاحتياط عبئًا غير مسبوق. الأهداف منخفضة جدًا والعقوبات ضعيفة، ويقول المنتقدون إنه يلتفّ على موقف المحكمة العليا بأن الإعفاء الشامل لا أساس قانونيًا له.",
    why:"بالنسبة إلى كثير من الناخبين، هي القضية الحاسمة في هذه الدورة."},
   ru:{title:"Закон о воинской службе: призыв учащихся иешив", short:"Призыв харедим", stage:"Голосование о преемственности · принят 63–57", sponsor:"Правительственный законопроект",
    sum:"Постепенно увеличит число ежегодно призываемых учащихся харедимных иешив — через коллективные квоты вместо личной обязанности — и снизит возраст освобождения от службы.",
    pro:"Только постепенный путь сработает, не разорвав харедимное общество. Изучение Торы само по себе служение народу, а принудительный массовый призыв уже проваливался.",
    con:"Закрепляет неравенство, когда резервисты несут беспрецедентную нагрузку. Квоты слишком низкие, санкции слишком слабые, и, по мнению критиков, закон обходит позицию Верховного суда о том, что у массового освобождения нет правовой основы.",
    why:"Для многих избирателей — главный вопрос этого созыва."}
  },
  src:[
   {t:"law", en:"Military Service Law (Amendment), bill text", he:"חוק שירות הביטחון (תיקון), נוסח ההצעה"},
   {t:"plen", en:"Plenum debate and continuity vote, 06.2024", he:"דיון במליאה והצבעה על דין רציפות, 06.2024"},
   {t:"cmte", en:"Foreign Affairs and Defence Committee, sessions on enlistment", he:"ועדת החוץ והביטחון, דיונים בנושא הגיוס"},
   {t:"data", en:"IDF manpower data presented to the committee", he:"נתוני כוח אדם של צה״ל שהוצגו בוועדה"},
   {t:"cmte", en:"Committee debate on the reservists’ burden", he:"דיון בוועדה על נטל המילואים"},
   {t:"court", en:"Supreme Court ruling on yeshiva student enlistment, 06.2024", he:"פסק דין בג״ץ בעניין גיוס תלמידי ישיבות, 06.2024"}
  ],
  deep:{
   en:[
    {h:0, p:[{x:"The bill sets annual enlistment targets for Haredi yeshiva students that rise over several years, measured for the community as a whole rather than as an obligation on each individual.", c:[1]},
             {x:"It lowers the age at which yeshiva students become permanently exempt, and ties part of yeshiva funding to meeting the targets. The vote shown here applied “continuity”, reviving a bill first tabled in the previous Knesset.", c:[1,2]}],
     q:{x:"“The annual enlistment target shall be… and shall rise each year as set out in the Schedule.”", s:"Bill text (translated)"}},
    {h:1, p:[{x:"Supporters, chiefly the Haredi parties and Likud, argued that change must be gradual and agreed; attempts at forced mass conscription have failed and would push the community away from the state.", c:[2,3]},
             {x:"Haredi speakers also argued that Torah study protects the nation in its own way and is a pillar of Jewish continuity.", c:[2]}],
     q:{x:"“You don’t build an army by breaking a community. You build it step by step.”", s:"Coalition MK · plenum, 06.2024"}},
    {h:2, p:[{x:"Opponents argued that the targets are too low and the sanctions too weak, and that after 7 October, with reservists serving hundreds of days, the burden cannot keep falling on only part of the public.", c:[4,5]},
             {x:"Some coalition members voiced reservations too. Critics also said the bill sidesteps the Supreme Court’s position that blanket exemptions have no legal basis.", c:[5,6]}],
     q:{x:"“Those who serve 250 days of reserve duty are not asking for gratitude. They are asking for partners.”", s:"Opposition MK · plenum, 06.2024"}},
    {h:3, p:[{x:"Drafted from the bill text, the plenum debate on continuity, Foreign Affairs and Defence Committee protocols, IDF manpower data presented to the committee, and the Supreme Court ruling of June 2024.", c:[]}]}
   ],
   he:[
    {h:0, p:[{x:"ההצעה קובעת יעדי גיוס שנתיים לתלמידי ישיבות חרדים, שעולים לאורך כמה שנים ונמדדים ברמת הציבור כולו ולא כחובה אישית של כל תלמיד.", c:[1]},
             {x:"היא מורידה את הגיל שבו תלמידי ישיבות מקבלים פטור קבוע, וקושרת חלק מתקציבי הישיבות לעמידה ביעדים. ההצבעה המוצגת כאן החילה ״דין רציפות״ על הצעה שהונחה לראשונה בכנסת הקודמת.", c:[1,2]}],
     q:{x:"״יעד הגיוס השנתי יהיה... ויעלה מדי שנה כמפורט בתוספת.״", s:"נוסח ההצעה"}},
    {h:1, p:[{x:"התומכים, בעיקר המפלגות החרדיות והליכוד, טענו שהשינוי חייב להיות הדרגתי ובהסכמה; ניסיונות לגיוס כפוי בהיקף רחב נכשלו, וירחיקו את הציבור החרדי מהמדינה.", c:[2,3]},
             {x:"דוברים חרדים טענו גם שלימוד התורה מגן על העם בדרכו שלו והוא עמוד תווך של ההמשכיות היהודית.", c:[2]}],
     q:{x:"״לא בונים צבא על ידי שבירת ציבור. בונים אותו צעד אחר צעד.״", s:"ח״כ מהקואליציה · מליאה, 06.2024"}},
    {h:2, p:[{x:"המתנגדים טענו שהיעדים נמוכים מדי והסנקציות חלשות מדי, ושאחרי 7 באוקטובר, כשאנשי מילואים משרתים מאות ימים, הנטל לא יכול להמשיך ליפול רק על חלק מהציבור.", c:[4,5]},
             {x:"גם חברי קואליציה אחדים הביעו הסתייגות. המבקרים טענו עוד שההצעה עוקפת את עמדת בג״ץ שלפיה אין בסיס חוקי לפטור גורף.", c:[5,6]}],
     q:{x:"״מי שעושה 250 ימי מילואים לא מבקש תודה. הוא מבקש שותפים.״", s:"ח״כ מהאופוזיציה · מליאה, 06.2024"}},
    {h:3, p:[{x:"נוסח מתוך נוסח ההצעה, הדיון במליאה על דין הרציפות, פרוטוקולים של ועדת החוץ והביטחון, נתוני כוח אדם של צה״ל שהוצגו בוועדה, ופסיקת בג״ץ מיוני 2024.", c:[]}]}
   ]
  }
}
]
};
